/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ForRoomSeriesIdImport } from './routes/for-room.series.$id'
import { Route as ForHouseSeriesIdImport } from './routes/for-house/series.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const ForHouseIndexLazyImport = createFileRoute('/for-house/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ForHouseIndexLazyRoute = ForHouseIndexLazyImport.update({
  path: '/for-house/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/for-house/index.lazy').then((d) => d.Route),
)

const ForRoomSeriesIdRoute = ForRoomSeriesIdImport.update({
  path: '/for-room/series/$id',
  getParentRoute: () => rootRoute,
} as any)

const ForHouseSeriesIdRoute = ForHouseSeriesIdImport.update({
  path: '/for-house/series/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/for-house/': {
      id: '/for-house/'
      path: '/for-house/'
      fullPath: '/for-house/'
      preLoaderRoute: typeof ForHouseIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/for-house/series/$id': {
      id: '/for-house/series/$id'
      path: '/for-house/series/$id'
      fullPath: '/for-house/series/$id'
      preLoaderRoute: typeof ForHouseSeriesIdImport
      parentRoute: typeof rootRoute
    }
    '/for-room/series/$id': {
      id: '/for-room/series/$id'
      path: '/for-room/series/$id'
      fullPath: '/for-room/series/$id'
      preLoaderRoute: typeof ForRoomSeriesIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  ForHouseIndexLazyRoute,
  ForHouseSeriesIdRoute,
  ForRoomSeriesIdRoute,
})

/* prettier-ignore-end */
